name = "moments-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "moments-db"
database_id = "6ffa1517-fe93-475a-ad2f-3e73d1ea9d90"

# R2 存储绑定
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "moments-storage"

# 环境变量
[vars]
JWT_SECRET = "qweasdzxc123"
CORS_ORIGIN = "https://moment.mcyzsx.top"
